### ISSUE TITLE
Allow patternProperties to not start with ^ and end with $

### ISSUE THREAD

**Issue by davidjulakidze** [ExodusMovement/schemasafe#173]
[Following the official documentation](https://json-schema.org/understanding-json-schema/reference/object#patternProperties) for 2020-12 draft and using the parser API.

when using "patternProperties" and specifying a regex that does not start with ^ and ends with $ I get the following error:
`Should start with ^ and end with $`

json schema supports patternProperties that do not end with $ as seen in the documentation. so the documentation example does not work when using parser API

```
{
  "type": "object",
  "patternProperties": {
    "^S_": { "type": "string" },
    "^I_": { "type": "integer" }
  }
}

```

**Comment by ChALkeR** [comment]
@davidjulakidze That check is enfored only in `requireValidation` | `requireStringValidation` modes, which is enabled by default in parser mode.

See [documentation on options](https://github.com/ExodusMovement/schemasafe/blob/master/doc/Options.md#regular-options).

The check for `^` `$` is just an additional safety measure against common mistakes in schemas, where e.g. `[a-z]*` is used as a pattern instead of `^[a-z]*$`, and the former is a no-op that matches _all_ strings.

Setting `mode` to `'default'` (or `'lax'`) will disable those additional safety checks (could be re-enabled individually).

**Comment by davidjulakidze** [comment]
let's say you wanted to allows any property that ends with "WithSuffix" would you be able to match a string like:

SomeRandomStringWithSuffix

Without turning strong mode off?

**Comment by ChALkeR** [comment]
If you expect __all__ characters (including newlines, whitespace, emojis, modifiers, weird unicode, etc.) before the suffix, then  `^[\s\S]*WithSuffix$`.

Otherwise, e.g. `^[a-zA-Z0-9_]*WithSuffix$` or similar, depending on which chars you expect

**Comment by davidjulakidze** [comment]
Aight, thank you for the clarification
